version: 2
jobs:
  build:
    working_directory: ~/afterWorks_v.4.0.0
    docker:
      - image: node:10.15.3
    steps:
      - checkout # レポジトリの取り込み

      # node-modules のキャッシュが存在すれば復元
      - restore_cache:
          name: Restore package cache
          keys:
            - dependency-cache-{{ checksum "package.json" }}
          working_directory: ~/afterWorks_v.4.0.0/nuxt/afterWorks_v.4.0.0/

      - run:
          name: npm install # npm install
          command: npm install
          working_directory: ~/afterWorks_v.4.0.0/nuxt/afterWorks_v.4.0.0/

      # node-modules をキャッシュ
      - save_cache:
          name: Save package cache
          paths:
            - ./node_modules
          key:
            dependency-cache-{{ checksum "package.json" }}
          working_directory: ~/afterWorks_v.4.0.0/nuxt/afterWorks_v.4.0.0/

      - run:
          name: npm run generate
          command: npm run generate
          working_directory: ~/afterWorks_v.4.0.0/nuxt/afterWorks_v.4.0.0/
      
      # generateした生成物をサーバに配置する
      - run: rsync -e "ssh -o StrictHostKeyChecking=no" -ahv ~/afterWorks_v.4.0.0/nuxt/afterWorks_v.4.0.0/dist/ ${DEPLOY_DEST}

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              # master ブランチ以外では deploy を実行しない
              only: master